name: addiction_tracker

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  emoji_picker_flutter: ^2.1.1
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
  adaptive_icon_background: "#020617"
  adaptive_icon_foreground: "images/logo.png"